<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="5" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-11T12:05:45Z" name="Suite" finished-at="2025-01-11T12:09:09Z" duration-ms="203665">
    <groups>
    </groups>
    <test started-at="2025-01-11T12:05:45Z" name="UploadTest" finished-at="2025-01-11T12:08:21Z" duration-ms="155965">
      <class name="Demo.Invoify.tests.verifyAttachmentUpload">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Demo.Invoify.tests.verifyAttachmentUpload@242aa8d9]" started-at="2025-01-11T12:05:45Z" name="launchApplication" finished-at="2025-01-11T12:06:22Z" duration-ms="37031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="testSignatureUpload()[pri:0, instance:Demo.Invoify.tests.verifyAttachmentUpload@242aa8d9]" started-at="2025-01-11T12:06:22Z" name="testSignatureUpload" finished-at="2025-01-11T12:07:35Z" duration-ms="72651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSignatureUpload -->
        <test-method signature="verifyBillAttachement()[pri:0, instance:Demo.Invoify.tests.verifyAttachmentUpload@242aa8d9]" started-at="2025-01-11T12:07:35Z" name="verifyBillAttachement" finished-at="2025-01-11T12:08:20Z" duration-ms="45125" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at Demo.Invoify.tests.verifyAttachmentUpload.verifyBillAttachement(verifyAttachmentUpload.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBillAttachement -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Demo.Invoify.tests.verifyAttachmentUpload@242aa8d9]" started-at="2025-01-11T12:08:21Z" name="quitDriver" finished-at="2025-01-11T12:08:21Z" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Demo.Invoify.tests.verifyAttachmentUpload -->
    </test> <!-- UploadTest -->
    <test started-at="2025-01-11T12:05:45Z" name="DataTest" finished-at="2025-01-11T12:09:06Z" duration-ms="200520">
      <class name="Demo.Invoify.tests.dataInputValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Demo.Invoify.tests.dataInputValidation@6d304f9d]" started-at="2025-01-11T12:05:45Z" name="launchApplication" finished-at="2025-01-11T12:06:22Z" duration-ms="37039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="testBankDetailsAreEntered()[pri:0, instance:Demo.Invoify.tests.dataInputValidation@6d304f9d]" started-at="2025-01-11T12:06:22Z" name="testBankDetailsAreEntered" finished-at="2025-01-11T12:07:42Z" duration-ms="80178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBankDetailsAreEntered -->
        <test-method signature="testProperTotalCalculation()[pri:0, instance:Demo.Invoify.tests.dataInputValidation@6d304f9d]" started-at="2025-01-11T12:07:42Z" name="testProperTotalCalculation" finished-at="2025-01-11T12:08:20Z" duration-ms="37528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProperTotalCalculation -->
        <test-method signature="testToggleButtonEnabling()[pri:0, instance:Demo.Invoify.tests.dataInputValidation@6d304f9d]" started-at="2025-01-11T12:08:20Z" name="testToggleButtonEnabling" finished-at="2025-01-11T12:09:05Z" duration-ms="45434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testToggleButtonEnabling -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Demo.Invoify.tests.dataInputValidation@6d304f9d]" started-at="2025-01-11T12:09:05Z" name="quitDriver" finished-at="2025-01-11T12:09:06Z" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Demo.Invoify.tests.dataInputValidation -->
    </test> <!-- DataTest -->
    <test started-at="2025-01-11T12:05:45Z" name="ActionTest" finished-at="2025-01-11T12:09:09Z" duration-ms="203665">
      <class name="Demo.Invoify.tests.validatingInvoiceActions">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Demo.Invoify.tests.validatingInvoiceActions@2c88b9fc]" started-at="2025-01-11T12:05:45Z" name="launchApplication" finished-at="2025-01-11T12:06:22Z" duration-ms="36681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="testInvoiceSaving()[pri:0, instance:Demo.Invoify.tests.validatingInvoiceActions@2c88b9fc]" started-at="2025-01-11T12:06:22Z" name="testInvoiceSaving" finished-at="2025-01-11T12:08:13Z" duration-ms="111147" status="SKIP">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='grid gap-1']/div[@class='text-sm font-semibold']"}
  (Session info: chrome=131.0.6778.265)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0c3cac223a8045163987f9b370b12295, findElement {using=xpath, value=//div[@class='grid gap-1']/div[@class='text-sm font-semibold']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.265, chrome: {chromedriverVersion: 131.0.6778.264 (2d05e315153..., userDataDir: /var/folders/zr/v2p23ft14w9...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54317}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:54317/devtoo..., se:cdpVersion: 131.0.6778.265, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 0c3cac223a8045163987f9b370b12295]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='grid gap-1']/div[@class='text-sm font-semibold']"}
  (Session info: chrome=131.0.6778.265)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0c3cac223a8045163987f9b370b12295, findElement {using=xpath, value=//div[@class='grid gap-1']/div[@class='text-sm font-semibold']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.265, chrome: {chromedriverVersion: 131.0.6778.264 (2d05e315153..., userDataDir: /var/folders/zr/v2p23ft14w9...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54317}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:54317/devtoo..., se:cdpVersion: 131.0.6778.265, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 0c3cac223a8045163987f9b370b12295
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy20.getText(Unknown Source)
at Demo.Invoify.Pages.actionAndPreviewPage.getMessage(actionAndPreviewPage.java:180)
at Demo.Invoify.tests.validatingInvoiceActions.testInvoiceSaving(validatingInvoiceActions.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvoiceSaving -->
        <test-method signature="testInvoiceSaving()[pri:0, instance:Demo.Invoify.tests.validatingInvoiceActions@2c88b9fc]" started-at="2025-01-11T12:08:13Z" name="testInvoiceSaving" finished-at="2025-01-11T12:08:59Z" duration-ms="46308" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your invoice has been generated!] but found [Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your invoice has been generated!] but found [Error]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Demo.Invoify.tests.validatingInvoiceActions.testInvoiceSaving(validatingInvoiceActions.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvoiceSaving -->
        <test-method signature="testNavigation()[pri:0, instance:Demo.Invoify.tests.validatingInvoiceActions@2c88b9fc]" started-at="2025-01-11T12:09:00Z" name="testNavigation" finished-at="2025-01-11T12:09:09Z" duration-ms="8562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNavigation -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Demo.Invoify.tests.validatingInvoiceActions@2c88b9fc]" started-at="2025-01-11T12:09:09Z" name="quitDriver" finished-at="2025-01-11T12:09:09Z" duration-ms="167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Demo.Invoify.tests.validatingInvoiceActions -->
    </test> <!-- ActionTest -->
  </suite> <!-- Suite -->
</testng-results>
